### PR TITLE
Adapt to API 30

### PR DESCRIPTION
**Pull request by WhiredPlanck**
# Overview
As many features and changes come up with new Android SDK version (latest is 32), our 19-target-SDK-version app seems to be a little out-of-date. This PR is to adapt it to Android SDK API level 30 (corresponds to Android 11).

# Main Changes
- Adapt to Scoped Storage feature.
- Use NDK to build C module with Gradle
  - Thus, the C module executable named `libscan.so` can be ran from app's native library directory directory, no need to chmod any more.
## Other small changes
- Introduction of Kotlin library, which enables developers to use Kotlin in the future.
- Build ProtoBuf with Gradle to manage version and generation easier.
- Replace some deprecated API usage, like non-recommended AsyncTask.
- Polish code style (not very useful :P).
- Regroup code files / polish tree structure.
- Update Chinese translations.
- Add About dialog.
- Use device default theme style to make look more modern.
- ...

# Test Result
LGTM on my Android 10 phone and pad.

## Screenshot
Screenshot_20220411_225511_com google android diskusage

Screenshot_20220411_230852_com google android diskusage

Screenshot_20220411_230846_com google android diskusage

### CODE REVIEW

**Comment by IvanVolosyuk** [comment]
Wow, that's a lot of changes. I will have a look. How's the compatibility
with older API versions?

**Comment by WhiredPlanck** [comment]
> Wow, that's a lot of changes. I will have a look. How's the compatibility with older API versions?

So sad that my old phone isn't working and I didn't test with old API versions yet. :rofl:  But I will manage to do tests soon.

**Comment by WhiredPlanck** [comment]
I've updated min SDK versiont to 21. This make new version app can be less concerned about the limitations of low API level.

And I've used the emulator to test, LGTM on API 21 (Android 5) and 28 (Android 9).

**Comment by IvanVolosyuk** [comment]
I merged this PR as it is much better than having non compiling broken source code.
I see a few breakages comparing to the version on play store for me (android 12, Pixel 4 XL):
* The app is crashing at the start as Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION) is not available. I defaulted to Android.M variant to get some permissions.

* Viewing files is not working. It seems the intent created is correct, but somehow viewer is not found. Not sure what google broke here this time.

* Only a few apps are displayed, the rest throwing exceptions and as a results all corresponding space is attributed to system data.

**Comment by WhiredPlanck** [comment]
> I merged this PR as it is much better than having non compiling broken source code. I see a few breakages comparing to the version on play store for me (android 12, Pixel 4 XL):
> 
>     * The app is crashing at the start as Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION) is not available. I defaulted to Android.M variant to get some permissions.
> 
>     * Viewing files is not working. It seems the intent created is correct, but somehow viewer is not found. Not sure what google broke here this time.
> 
>     * Only a few apps are displayed, the rest throwing exceptions and as a results all corresponding space is attributed to system data.

As far as I know, Android 12 has some breaking changes in some way which is a little difficult to figure out.
On Android 10 and below，`Android/data` in Internal Storage is still accessible like other scopes, so this part will be duplicate with the `Apps` part in the view. And viewing files has been broken already before I work on this PR. I don't want to make this PR too complex so I doesn't fix them. (Actually I also have no idea to workaround them 🤣 )

**Comment by IvanVolosyuk** [comment]
As I said, this entire effort became a compatibility nightmare. Android
doesn't seem to provide a stable API for apps like this and it is just
frustrating to make anything work especially if you don't have access to a
pool of test devices.

**Pull request merged**
