### PR TITLE
Rename Application ID

### PR DESCRIPTION
**Pull request by WhiredPlanck**
This PR is going to rename the application id, because the current `com.google.android.diskusage` looks like a Google official product, and it may cause a misunderstanding, so I rename it to `com.volosyukivan.diskusage`.

This PR is based on #79 , you may want to merge it first.

### CODE REVIEW

**Comment by IvanVolosyuk** [comment]
I don't think I can rename it on play store.

**Comment by WhiredPlanck** [comment]
> I don't think I can rename it on play store.

Hm, have you lost control of the Google Play version ... ? Or other reason?

**Comment by IvanVolosyuk** [comment]
I think google play doesn't allow you to change package version for an app,
but I might be mistaken. Haven't tried that.

**Comment by WhiredPlanck** [comment]
> I think google play doesn't allow you to change package version for an app, but I might be mistaken. Haven't tried that.

It doesn't matter. I just try to do it. If Google Play doesn't allow us or it's too much trouble to do that, just close this PR.

**Pull request closed without merging**
